### ISSUE TITLE
Getting errors while importing whylabs module

### ISSUE THREAD

**Issue by ajinkya2903** [eeeds/employees-attrition-mlops#2]
I am trying to run model.py but I am getting errors while importing modelType and WhyLabsWriter. Can anyone tell me how to import these modules properly. Thanks

**Comment by eeeds** [comment]
> I am trying to run model.py but I am getting errors while importing modelType and WhyLabsWriter. Can anyone tell me how to import these modules properly. Thanks

Hi @ajinkya2903. I think Whylabs v0 is no longer supported. I'll try to fix this error by upgrading to v1.

**Comment by ajinkya2903** [comment]
Hi @eeeds Thanks for the response. I have solved the issue and the solution was to downgrade python version. Initially it was python 3.10 and thus it was not getting installed but then I downgraded it to python 3.7 it worked.

**Comment by ajinkya2903** [comment]
But after this when I am running **python model.py** I am getting this error!
![image](https://user-images.githubusercontent.com/63385842/208378150-b7ed3c49-cc3e-4e83-8a89-5e379d1f2675.png)
May I know what mistake I am doing and what is the correct way of doing this. I want to see how it is running end to end so just following the steps given in the readme section. Thanks

**Comment by eeeds** [comment]
I havent't seen that error before, but it could be something related to your mlflow configuration. Have you tracked your mlflow to a db, for example: `mlflow.set_tracking_uri('sqlite:///mydb.sqlite')`.

I think you should try run it using a virtual enviroment such as conda or pipenv in order to follow good practices.

**Comment by ajinkya2903** [comment]
Hi @eeeds. Don't know what is that issue so started working in virtual env but after that getting this issue(attached SS). Maybe this is related to mlflow version. Latest version is giving above mentioned error but when I downgraded the version it is giving this new error. Have you ever encountered this before?
<img width="911" alt="image" src="https://user-images.githubusercontent.com/63385842/208654313-6d103797-b67c-4021-8b53-1b049783b1c0.png">

**Comment by eeeds** [comment]
> Hi @eeeds. Don't know what is that issue so started working in virtual env but after that getting this issue(attached SS). Maybe this is related to mlflow version. Latest version is giving above mentioned error but when I downgraded the version it is giving this new error. Have you ever encountered this before? <img alt="image" width="911" src="https://user-images.githubusercontent.com/63385842/208654313-6d103797-b67c-4021-8b53-1b049783b1c0.png">

Hi @ajinkya2903, sorry for my late reply. I hadn't encountered that error before. It's something new to me. Can you send me your code or can you publish it on github?
I'd like to run it and see what I get.

**Comment by ajinkya2903** [comment]
Hi @eeeds. I have actually cloned your repo and started following the steps mentioned in the ReadME section. But dont know why it is not running and I am getting the above error. This is my cloned repo https://github.com/ajinkya2903/employee_attrition. Do check it and let me know what mistake I am doing and how to solve it.
Python Version : 3.9.13
Mlflow Version : 2.0.1

**Comment by eeeds** [comment]
Hi, @ajinkya2903. Sorry. I was on vacation and I wasn't able to try your code. Did you solve the problem?
